import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className={`bg-white flex w-screen justify-between inline-flex p-1 px-16 fixed `}>
          <Image src={`https://comma.ai/icon-menu-2.svg`} layout={"fixed"} width={`28rem`} height={60} alt={`navbar image`} />
          <img className={`pl-16 h-14`} src={`https://avatars.githubusercontent.com/u/16128714?s=280&v=4`} alt={`navbar image`} />
          <button className="bg-comma-green text-comma-gray text-black font-bold py-2.5 my-2 text-md px-5 rounded">
            Shop
          </button>
        </nav>
        <div style={{'paddingTop': '2rem', 'paddingBottom': '1.9rem'}} className={`bg-white flex w-screen justify-between inline-flex px-14`} />
        <p className={`bg-comma-bright-green w-screen text-xl text-center p-4 py-5`}>
          The comma body is here. Learn More -&gt;
        </p>
        <p style={{top: '8rem', 'line-height': '65%'}} className={`text-white w-screen mt-19 text-center text-6.5xl font-monument`}>
          COMMA THREE<br/>
          <span className={`font-inter-light opacity-80 text-xl`}>Make driving chill with our beautiful new hardware.</span><br/>
          <span className={`font-inter text-2xl text-comma-green`} style={{'line-height': '6rem'}}>Buy Now &gt;</span>
        </p>
        <div className={`w-screen flex justify-center mt-3`}>
          <Image src={'https://comma.ai/c3-homepage.png'} priority={true} height={'590px'} width={'945.3px'} quality={100} alt={''}/>
          <video style={{'vertical-align': 'top'}} className={`absolute mt-2`} src={'https://comma.ai/c3screen.mp4'} height={'420px'} width={'875.3px'} autoPlay muted loop controls={false}/>
        </div>
        <p className={`text-white w-screen text-center text-4xl font-inter-light text-gray-300`}>
          Unlike many OEM ADAS systems, openpilot can drive for hours<br/>
          without intervention. We sell a devkit that can run openpilot with 360°<br/>
          HDR vision, compatible with 150+ cars. Starting at $1999. <span>Buy Now &gt;</span>
        </p>
      </main>
    </div>
  )
}
